server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true  
    hibernate:
      ddl-auto: create
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${url}
    username: root
    password: mysql1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: reservationStatus
          destination: parkingTicket
          contentType: application/json
        event-out:
          destination: parkingTicket
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084
---

spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${url}
    username: root
    password: mysql1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: reservationStatus
          destination: parkingTicket
          contentType: application/json
        event-out:
          destination: parkingTicket
          contentType: application/json
